import img1 from "@assets/e36ce9bb-0d6b-47ca-bdf3-543e32f0c7db_1780554304602.jpeg";
import img2 from "@assets/77860941-86bc-424c-b723-329270eb094c_1780554304613.jpeg";
import img3 from "@assets/7c02788d-42ae-4f64-ac09-cba0e006985e_1780554304630.jpeg";
import img4 from "@assets/30c54746-6885-4533-a1f7-7f3b5277a493_1780554304648.jpeg";
import img5 from "@assets/01ebc7cd-f4ed-41d3-b920-8ee62d6c65c8_1780554304664.jpeg";
import img6 from "@assets/bb24dc90-e209-4968-a707-ed74824321b9_1780554304682.jpeg";
import img7 from "@assets/f081ad12-949c-4a9f-8f81-5179b9507147_1780554304696.jpeg";
import img8 from "@assets/2a4d9263-fcdd-40c5-a2c3-ff49896e7553_1780554304711.jpeg";
import img9 from "@assets/e12413a7-90b6-4158-9ea8-7434d36d8e29_1780554304735.jpeg";
import img10 from "@assets/135cd6d9-874a-4d8d-9735-036390a6c5d6_1780554304762.jpeg";
import img11 from "@assets/7168813c-ea4b-41f9-b4db-e92f3b83ebb6_1780554304777.jpeg";
import img12 from "@assets/4ad25d77-b65f-49aa-a138-be9e9e82e58f_1780554304790.jpeg";
import img13 from "@assets/7cf7d23d-5478-45ec-9fcc-d93f270e4602_1780554304807.jpeg";

export interface MockProduct {
  id: number;
  title: string;
  slug: string;
  price: number;
  mrp: number;
  mainImage: string;
  images: string[];
  artisanName: string;
  artisan: {
    name: string;
    slug: string;
    photo: string | null;
    craftType: string;
    state: string;
    shortBio: string;
  };
  rating: number;
  reviewCount: number;
  isNewArrival: boolean;
  isBestSeller: boolean;
  inStock: boolean;
  stockQuantity: number;
  freeShipping: boolean;
  shortDescription: string;
  description: string;
  careInstructions: string;
  material: string;
  placeOfOrigin: string;
  weight: number;
  categorySlug: string;
  categoryName: string;
}

export const MOCK_PRODUCTS: MockProduct[] = [
  {
    id: 101,
    title: "Madhubani Painted Silk Dupatta",
    slug: "madhubani-painted-silk-dupatta",
    price: 1850,
    mrp: 2499,
    mainImage: img1,
    images: [img1],
    artisanName: "Sunita Devi",
    artisan: { name: "Sunita Devi", slug: "sunita-devi", photo: null, craftType: "Madhubani Painting", state: "Bihar", shortBio: "Sunita Devi hails from Mithila, Bihar — the heartland of Madhubani art. She has been practising this 2,500-year-old tradition for over 20 years, using natural pigments to create intricate mythological motifs on silk and hand-made paper." },
    rating: 4.8,
    reviewCount: 142,
    isNewArrival: false,
    isBestSeller: true,
    inStock: true,
    stockQuantity: 12,
    freeShipping: true,
    shortDescription: "A luxurious hand-painted Madhubani dupatta on pure silk, adorned with traditional Mithila motifs of peacocks and lotus flowers in vibrant natural colours.",
    description: "Each Madhubani dupatta is a labour of love — hand-painted by master artisan Sunita Devi using organic colours derived from turmeric, indigo, and lac. The iconic peacock and fish motifs represent love and fertility in Mithila tradition.\n\nMade on pure Kanchivaram silk, this dupatta is both a wearable art piece and a collectible. No two pieces are identical, making yours truly one-of-a-kind.",
    careInstructions: "Dry clean only. Store in a cool, dry place. Avoid direct sunlight for prolonged periods to preserve colour vibrancy.",
    material: "Pure Silk",
    placeOfOrigin: "Madhubani, Bihar",
    weight: 120,
    categorySlug: "textiles",
    categoryName: "Textiles",
  },
  {
    id: 102,
    title: "Warli Tribal Wall Canvas",
    slug: "warli-tribal-wall-canvas",
    price: 1299,
    mrp: 1799,
    mainImage: img2,
    images: [img2],
    artisanName: "Ramesh Tumbada",
    artisan: { name: "Ramesh Tumbada", slug: "ramesh-tumbada", photo: null, craftType: "Warli Painting", state: "Maharashtra", shortBio: "Ramesh Tumbada is a 3rd-generation Warli painter from the Dahanu region of Maharashtra. His geometric depictions of village life — harvests, dances, and weddings — have been exhibited across India and Europe." },
    rating: 4.6,
    reviewCount: 89,
    isNewArrival: true,
    isBestSeller: false,
    inStock: true,
    stockQuantity: 20,
    freeShipping: false,
    shortDescription: "Authentic Warli tribal painting on handmade canvas depicting the vibrant harvest dance (Tarpa) of Maharashtra's Adivasi communities.",
    description: "Warli is one of India's most ancient art forms, practised by the tribal communities of the Sahyadri mountains. This canvas by Ramesh Tumbada showcases the iconic Tarpa dance — a circular formation symbolising the cycle of life.\n\nPainted using rice paste on an earthy brown canvas, the stark white geometric figures carry a timeless, meditative quality. A perfect statement piece for living rooms and offices.",
    careInstructions: "Wipe gently with a dry cloth. Keep away from moisture. Frame under UV-protective glass for best preservation.",
    material: "Handmade Canvas, Rice Paste Colours",
    placeOfOrigin: "Dahanu, Maharashtra",
    weight: 200,
    categorySlug: "paintings",
    categoryName: "Paintings & Wall Art",
  },
  {
    id: 103,
    title: "Dhokra Brass Tribal Elephant",
    slug: "dhokra-brass-tribal-elephant",
    price: 2200,
    mrp: 2999,
    mainImage: img3,
    images: [img3],
    artisanName: "Bikash Mahato",
    artisan: { name: "Bikash Mahato", slug: "bikash-mahato", photo: null, craftType: "Dhokra Casting", state: "West Bengal", shortBio: "Bikash Mahato belongs to the Dhokra Damar tribe of West Bengal and has been practising the 4,000-year-old lost-wax casting technique since childhood. His intricate figurines have won him the National Award for Master Craftsmen." },
    rating: 4.9,
    reviewCount: 203,
    isNewArrival: false,
    isBestSeller: true,
    inStock: true,
    stockQuantity: 8,
    freeShipping: true,
    shortDescription: "A beautifully cast Dhokra brass elephant using the ancient lost-wax (cire perdue) technique — one of humanity's oldest metal casting methods, over 4,000 years old.",
    description: "The Dhokra elephant is cast using the cire perdue (lost-wax) process — beeswax is sculpted, coated in clay, and molten brass is poured in. Each piece is unique because the mould is broken after casting.\n\nThis majestic elephant, adorned with traditional tribal motifs, symbolises strength, wisdom, and prosperity. A prized gift and décor piece that carries centuries of heritage.",
    careInstructions: "Wipe with a soft dry cloth. Apply a thin coat of linseed oil occasionally to maintain lustre. Avoid exposure to harsh chemicals.",
    material: "Brass (Dhokra Cast)",
    placeOfOrigin: "Bankura, West Bengal",
    weight: 650,
    categorySlug: "metalwork",
    categoryName: "Metalwork & Sculptures",
  },
  {
    id: 104,
    title: "Rajasthani Block Print Bed Cover",
    slug: "rajasthani-block-print-bed-cover",
    price: 2750,
    mrp: 3500,
    mainImage: img4,
    images: [img4],
    artisanName: "Farida Khatoon",
    artisan: { name: "Farida Khatoon", slug: "farida-khatoon", photo: null, craftType: "Block Printing", state: "Rajasthan", shortBio: "Farida Khatoon is a master block printer from Sanganer, the block-printing capital of India. She uses hand-carved teak wood blocks and natural dyes to create intricate floral patterns that have adorned Rajasthani homes for generations." },
    rating: 4.7,
    reviewCount: 167,
    isNewArrival: false,
    isBestSeller: true,
    inStock: true,
    stockQuantity: 15,
    freeShipping: true,
    shortDescription: "Double-bed cover in breathable cotton, hand block-printed with the classic Bagru floral motif using natural indigo and madder dyes. Each block impression is unique.",
    description: "Sanganer block printing is a 500-year-old tradition passed down through generations of Chhipa artisans. Farida Khatoon uses hand-carved wooden blocks and natural dyes — indigo from plants, madder from roots — to create her signature floral patterns.\n\nThis queen-size bed cover (90x108 inches) is made from 100% breathable cotton and gets softer with every wash. The slight imperfections are proof of the human hand — making it art you sleep on.",
    careInstructions: "Machine wash cold with mild detergent. Do not bleach. Tumble dry low or line dry. Iron on medium heat.",
    material: "100% Cotton",
    placeOfOrigin: "Sanganer, Rajasthan",
    weight: 800,
    categorySlug: "textiles",
    categoryName: "Textiles",
  },
  {
    id: 105,
    title: "Bidriware Silver Inlay Vase",
    slug: "bidriware-silver-inlay-vase",
    price: 3800,
    mrp: 4999,
    mainImage: img5,
    images: [img5],
    artisanName: "Mohammad Hasan",
    artisan: { name: "Mohammad Hasan", slug: "mohammad-hasan", photo: null, craftType: "Bidriware", state: "Karnataka", shortBio: "Mohammad Hasan is a 5th-generation Bidriware craftsman from Bidar, Karnataka. His family has been creating this distinctive zinc alloy with silver inlay craft for over 150 years, serving royal courts and now global collectors." },
    rating: 5.0,
    reviewCount: 58,
    isNewArrival: true,
    isBestSeller: false,
    inStock: true,
    stockQuantity: 5,
    freeShipping: true,
    shortDescription: "A stunning Bidriware vase crafted from zinc alloy with pure silver inlay, featuring traditional Arabesque floral patterns. GI-tagged craft from Bidar, Karnataka.",
    description: "Bidriware is one of India's most distinctive metalwork traditions — GI-tagged and over 600 years old. The craft involves casting a zinc-copper alloy, engraving intricate floral and geometric patterns, and inlaying pure silver wire into the grooves.\n\nThe final piece is treated with a unique mud paste from Bidar that permanently oxidises the alloy to jet black, making the silver inlay gleam brilliantly. This vase takes 15–20 hours to complete by hand.",
    careInstructions: "Wipe gently with a soft cloth. Do not use abrasive cleaners. Keep away from moisture to preserve the oxidised finish.",
    material: "Zinc-Copper Alloy, Pure Silver",
    placeOfOrigin: "Bidar, Karnataka",
    weight: 420,
    categorySlug: "metalwork",
    categoryName: "Metalwork & Sculptures",
  },
  {
    id: 106,
    title: "Kalamkari Hand-Painted Saree",
    slug: "kalamkari-hand-painted-saree",
    price: 4500,
    mrp: 5999,
    mainImage: img6,
    images: [img6],
    artisanName: "Lakshmi Narayana",
    artisan: { name: "Lakshmi Narayana", slug: "lakshmi-narayana", photo: null, craftType: "Kalamkari", state: "Andhra Pradesh", shortBio: "Lakshmi Narayana is a National Award-winning Kalamkari artist from Srikalahasti, Andhra Pradesh. Her work is featured in the collection of the National Crafts Museum, New Delhi." },
    rating: 4.8,
    reviewCount: 91,
    isNewArrival: true,
    isBestSeller: false,
    inStock: true,
    stockQuantity: 6,
    freeShipping: true,
    shortDescription: "A masterwork Srikalahasti Kalamkari saree hand-drawn with a bamboo pen using natural dyes — depicting the Dashavatar (ten avatars of Lord Vishnu).",
    description: "Srikalahasti Kalamkari (kalam = pen, kari = work) involves drawing freehand with a bamboo pen soaked in fermented jaggery and iron water on cotton treated with myrobalan. No two sarees are ever the same.\n\nThis 6-metre saree depicts the Dashavatar across the pallu and border, with each avatar's story told through detailed narrative scenes. The colours are derived entirely from natural sources: pomegranate skin, indigo, and turmeric.",
    careInstructions: "Hand wash separately in cold water with mild soap. Do not wring. Dry in shade. Do not use fabric softener or bleach.",
    material: "Handwoven Cotton",
    placeOfOrigin: "Srikalahasti, Andhra Pradesh",
    weight: 450,
    categorySlug: "textiles",
    categoryName: "Textiles",
  },
  {
    id: 107,
    title: "Pattachitra Wooden Wall Panel",
    slug: "pattachitra-wooden-wall-panel",
    price: 3200,
    mrp: 4200,
    mainImage: img7,
    images: [img7],
    artisanName: "Aparna Mahapatra",
    artisan: { name: "Aparna Mahapatra", slug: "aparna-mahapatra", photo: null, craftType: "Pattachitra", state: "Odisha", shortBio: "Aparna Mahapatra comes from the hereditary Chitrakara (painter) community of Raghurajpur — India's only craft village where every household is an artist. She has been practising Pattachitra for 25 years." },
    rating: 4.7,
    reviewCount: 134,
    isNewArrival: false,
    isBestSeller: true,
    inStock: true,
    stockQuantity: 10,
    freeShipping: false,
    shortDescription: "Exquisite Pattachitra wooden panel depicting the Dashavatara in traditional Odishan style, painted with stone colours and natural lacquer varnish.",
    description: "Pattachitra ('patta' = cloth/wood, 'chitra' = picture) is an ancient Odishan painting tradition dating back to the 5th century CE. Aparna Mahapatra prepares her own colours from conch shells, lamp black, and precious stones.\n\nThis hardwood panel is primed with tamarind paste and chalk powder before painting. The intricate border of creepers and flowers follows the strict grammatical rules of the tradition. A GI-tagged craft directly from the artist's home-studio in Raghurajpur village.",
    careInstructions: "Dust with a soft dry brush. Do not use water or cleaning agents on the painted surface. Hang away from direct sunlight.",
    material: "Sal Wood, Stone Colours, Natural Lacquer",
    placeOfOrigin: "Raghurajpur, Odisha",
    weight: 900,
    categorySlug: "paintings",
    categoryName: "Paintings & Wall Art",
  },
  {
    id: 108,
    title: "Pashmina Embroidered Stole",
    slug: "pashmina-embroidered-stole",
    price: 5800,
    mrp: 7500,
    mainImage: img8,
    images: [img8],
    artisanName: "Abdul Rashid Bhat",
    artisan: { name: "Abdul Rashid Bhat", slug: "abdul-rashid-bhat", photo: null, craftType: "Kashmiri Embroidery", state: "Jammu & Kashmir", shortBio: "Abdul Rashid Bhat is a master Sozni embroiderer from Srinagar with over 35 years of experience. He specialises in the needle-fine sozni stitch that can take months to complete a single shawl." },
    rating: 4.9,
    reviewCount: 176,
    isNewArrival: false,
    isBestSeller: true,
    inStock: true,
    stockQuantity: 7,
    freeShipping: true,
    shortDescription: "100% pure Pashmina stole with hand-embroidered Sozni work (needle embroidery) featuring the iconic Chinar leaf and Badam motifs — a true Kashmir heirloom.",
    description: "Pashmina wool comes from the underbelly of the Changthangi goat, herded at altitudes above 14,000 feet in Ladakh. Each strand is thinner than a human hair, making genuine Pashmina impossibly soft and warm.\n\nThis stole features Sozni embroidery — the most intricate form of Kashmiri needlework, done with a single needle on both sides of the fabric. The Chinar leaf and Badam (almond) motifs took Abdul Rashid Bhat's family workshop over 3 months to complete.",
    careInstructions: "Dry clean recommended. If hand washing, use lukewarm water with baby shampoo. Do not wring. Dry flat. Store folded with a cedar block to deter moths.",
    material: "100% Pure Pashmina",
    placeOfOrigin: "Srinagar, Kashmir",
    weight: 180,
    categorySlug: "textiles",
    categoryName: "Textiles",
  },
  {
    id: 109,
    title: "Blue Pottery Decorative Plate Set",
    slug: "blue-pottery-decorative-plate-set",
    price: 1650,
    mrp: 2200,
    mainImage: img9,
    images: [img9],
    artisanName: "Gopal Saini",
    artisan: { name: "Gopal Saini", slug: "gopal-saini", photo: null, craftType: "Blue Pottery", state: "Rajasthan", shortBio: "Gopal Saini is a 4th-generation blue pottery artisan from Jaipur. His workshop in the Sanganer area has been producing the distinctive Turko-Persian inspired pottery for over 80 years." },
    rating: 4.5,
    reviewCount: 112,
    isNewArrival: true,
    isBestSeller: false,
    inStock: true,
    stockQuantity: 22,
    freeShipping: false,
    shortDescription: "Set of 4 hand-crafted Jaipur Blue Pottery decorative plates in cobalt blue and white, featuring floral motifs. Made without clay — using quartz, glass, and Multani mitti.",
    description: "Jaipur Blue Pottery is unique — unlike most ceramics, it uses no clay. The base is quartz stone powder, recycled glass, and fuller's earth (Multani mitti), giving it a distinctive translucent blue-white appearance.\n\nThe vivid cobalt and turquoise floral motifs are painted by hand before a low-temperature glaze firing. Set includes 4 plates (8 inches diameter) — perfect as décor, fruit bowls, or serving platters.",
    careInstructions: "Gently hand wash with mild soap and lukewarm water. Do not soak. Not microwave or dishwasher safe. Handle with care as the quartz-based body can chip.",
    material: "Quartz, Glass, Fuller's Earth",
    placeOfOrigin: "Jaipur, Rajasthan",
    weight: 600,
    categorySlug: "pottery",
    categoryName: "Pottery & Ceramics",
  },
  {
    id: 110,
    title: "Kondapalli Wooden Toy Set",
    slug: "kondapalli-wooden-toy-set",
    price: 890,
    mrp: 1199,
    mainImage: img10,
    images: [img10],
    artisanName: "Narsimha Rao",
    artisan: { name: "Narsimha Rao", slug: "narsimha-rao", photo: null, craftType: "Kondapalli Toys", state: "Andhra Pradesh", shortBio: "Narsimha Rao is from the Aryakhatriya community of Kondapalli — the only community trained in this 400-year-old craft. He uses the soft tella poniki wood that grows only on the Eastern Ghats." },
    rating: 4.6,
    reviewCount: 78,
    isNewArrival: true,
    isBestSeller: false,
    inStock: true,
    stockQuantity: 18,
    freeShipping: false,
    shortDescription: "Colourful set of 6 Kondapalli wooden toys — bullock cart, farmer, cow, and village figurines — hand-carved from the rare tella poniki softwood of the Eastern Ghats.",
    description: "Kondapalli toys (GI-tagged) have delighted children and collectors for 400 years. Carved from the uniquely soft tella poniki wood, these toys are lightweight and brightly painted using water-based colours.\n\nEach toy is shaped without a lathe — just a small knife and chisel. This set includes 6 pieces depicting rural Indian life and is suitable for children aged 3+ and adults who appreciate folk art.",
    careInstructions: "Wipe with a dry cloth only. Keep away from moisture. Not suitable for children under 3 (small parts). The colours are non-toxic and water-based.",
    material: "Tella Poniki Softwood",
    placeOfOrigin: "Kondapalli, Andhra Pradesh",
    weight: 250,
    categorySlug: "woodcraft",
    categoryName: "Woodcraft & Toys",
  },
  {
    id: 111,
    title: "Channapatna Lacquered Rattle & Spinning Top",
    slug: "channapatna-lacquered-rattle",
    price: 699,
    mrp: 950,
    mainImage: img11,
    images: [img11],
    artisanName: "Manjunath G.",
    artisan: { name: "Manjunath G.", slug: "manjunath-g", photo: null, craftType: "Channapatna Toys", state: "Karnataka", shortBio: "Manjunath G. is a master toy-maker from Channapatna — the 'Toy Town of Karnataka' established by Tipu Sultan in the 18th century. He works on a traditional pole lathe, using natural vegetable lacquers." },
    rating: 4.7,
    reviewCount: 95,
    isNewArrival: false,
    isBestSeller: true,
    inStock: true,
    stockQuantity: 30,
    freeShipping: false,
    shortDescription: "Handcrafted Channapatna lacquerware rattle and spinning top set, turned on a traditional pole lathe using ivory wood and natural vegetable-based lacquers. GI-tagged.",
    description: "Channapatna (Karnataka) has been making lacquered wooden toys since the time of Tipu Sultan, who invited Persian craftsmen to train local artisans. Today it is a GI-protected craft.\n\nThe toys are turned on a pole lathe (hand-powered, no electricity!) from ivory wood, then decorated with vegetal lac in vivid, non-toxic colours. This rattle and spinning top set is safe for babies and a delight for collectors.",
    careInstructions: "Wipe with a soft damp cloth. Do not submerge. The natural lacquer finish is food-safe and non-toxic.",
    material: "Ivory Wood, Vegetable Lac",
    placeOfOrigin: "Channapatna, Karnataka",
    weight: 150,
    categorySlug: "woodcraft",
    categoryName: "Woodcraft & Toys",
  },
  {
    id: 112,
    title: "Bamboo Woven Storage Basket Set",
    slug: "bamboo-woven-storage-basket-set",
    price: 1250,
    mrp: 1699,
    mainImage: img12,
    images: [img12],
    artisanName: "Sangma Rakshi",
    artisan: { name: "Sangma Rakshi", slug: "sangma-rakshi", photo: null, craftType: "Bamboo Weaving", state: "Meghalaya", shortBio: "Sangma Rakshi is a weaver from the Garo Hills of Meghalaya. Her community has woven bamboo baskets for generations, using sustainable bamboo from their own forests. She leads a women's cooperative of 40 weavers." },
    rating: 4.5,
    reviewCount: 63,
    isNewArrival: true,
    isBestSeller: false,
    inStock: true,
    stockQuantity: 25,
    freeShipping: false,
    shortDescription: "Set of 3 nesting bamboo storage baskets with lids, hand-woven by the Garo tribal women of Meghalaya using sustainably harvested bamboo. Perfect for kitchen or home décor.",
    description: "Bamboo weaving is the backbone of the northeast Indian economy. These storage baskets are hand-woven by Sangma Rakshi's women's cooperative in the Garo Hills — using bamboo harvested from sustainable community forests.\n\nThe nesting set (S/M/L) features a traditional diagonal weave and natural brown-on-cream patterns. Treated with food-safe lemon oil, these baskets are perfect for organising kitchens, bathrooms, or dressers.",
    careInstructions: "Wipe with a damp cloth. Dry immediately. Do not soak or expose to prolonged moisture. Occasional light oiling with lemon oil keeps the bamboo supple.",
    material: "Natural Bamboo, Cane",
    placeOfOrigin: "Garo Hills, Meghalaya",
    weight: 400,
    categorySlug: "bamboo-craft",
    categoryName: "Bamboo & Cane Craft",
  },
  {
    id: 113,
    title: "Terracotta Wind Chime — Temple Bells",
    slug: "terracotta-wind-chime-temple-bells",
    price: 599,
    mrp: 849,
    mainImage: img13,
    images: [img13],
    artisanName: "Kavitha Reddy",
    artisan: { name: "Kavitha Reddy", slug: "kavitha-reddy", photo: null, craftType: "Terracotta Work", state: "Tamil Nadu", shortBio: "Kavitha Reddy is a terracotta artisan from Pudukottai, Tamil Nadu, known for her musical clay wind chimes. She creates each clay bell by hand, tuning them to produce gentle, melodious notes when struck by the wind." },
    rating: 4.6,
    reviewCount: 147,
    isNewArrival: true,
    isBestSeller: false,
    inStock: true,
    stockQuantity: 40,
    freeShipping: false,
    shortDescription: "Handcrafted terracotta wind chime with 7 clay temple bells hand-painted with Tanjore-inspired motifs in ochre, ivory, and turquoise. Each bell produces a gentle, musical tone.",
    description: "These terracotta wind chimes from Pudukottai, Tamil Nadu blend the earthy warmth of hand-moulded clay with the meditative sound of temple bells. Each of the 7 bells is individually shaped, sun-dried, kiln-fired, and then hand-painted with motifs inspired by Tanjore art.\n\nKavitha Reddy tunes each bell by adjusting its wall thickness during shaping — a skill that took her years to master. Hung indoors or on a balcony, the gentle chiming creates a peaceful, grounded atmosphere.",
    careInstructions: "Suitable for covered outdoor use. Bring indoors during heavy rain. Dust gently with a soft brush. Do not wash — terracotta absorbs water.",
    material: "Terracotta, Natural Earth Pigments",
    placeOfOrigin: "Pudukottai, Tamil Nadu",
    weight: 300,
    categorySlug: "pottery",
    categoryName: "Pottery & Ceramics",
  },
];

export const BEST_SELLERS = MOCK_PRODUCTS.filter(p => p.isBestSeller);
export const NEW_ARRIVALS = MOCK_PRODUCTS.filter(p => p.isNewArrival);

export function getProductBySlug(slug: string): MockProduct | undefined {
  return MOCK_PRODUCTS.find(p => p.slug === slug);
}

export function toProductCard(p: MockProduct) {
  return {
    id: p.id,
    title: p.title,
    slug: p.slug,
    price: p.price,
    mrp: p.mrp,
    mainImage: p.mainImage,
    artisanName: p.artisanName,
    rating: p.rating,
    reviewCount: p.reviewCount,
    isNewArrival: p.isNewArrival,
    isBestSeller: p.isBestSeller,
    inStock: p.inStock,
  };
}
